# Generated by Django 6.0.3 on 2026-03-29 23:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waiting_room', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='waitingroomentry',
            options={'ordering': ['priority', 'created_at']},
        ),
        migrations.RenameField(
            model_name='waitingroomentry',
            old_name='added_at',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='waitingroomentry',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='waitingroomentry',
            name='added_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiting_entries_added', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='waitingroomentry',
            name='priority',
            field=models.IntegerField(choices=[(1, 'Emergency'), (2, 'Appointment'), (3, 'Normal')], default=3),
        ),
    ]
