# Generated by Django 6.0.3 on 2026-04-17 14:57

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='consultation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), help_text='Default consultation fee for doctors.', max_digits=12),
        ),
    ]
