# Generated by Django 6.0.3 on 2026-04-17 19:19

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_consultation_fee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='consultation_fee',
        ),
        migrations.AddField(
            model_name='user',
            name='doctor_consultation_fee',
            field=models.DecimalField(decimal_places=2, default=Decimal('5000.00'), max_digits=12),
        ),
    ]
