# Generated by Django 6.0.3 on 2026-03-31 15:41

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
        ('consultations', '0002_consultation_prescriptions'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing',
            name='prescription_total',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AlterField(
            model_name='billing',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='billing', to='consultations.consultation'),
        ),
    ]
