# Generated by Django 6.0.3 on 2026-04-03 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('laboratory', '0001_initial'),
        ('patients', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='labrequest',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='labrequest',
            name='requested_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='doctor_reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='lab_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='laboratory.labrequest'),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labresultattachment',
            name='lab_request_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='laboratory.labrequestitem'),
        ),
        migrations.AddField(
            model_name='labresultattachment',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_result_attachments_uploaded', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='labrequestitem',
            name='lab_test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_items', to='laboratory.labtest'),
        ),
    ]
