# Generated by Django 6.0.3 on 2026-04-14 19:53

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LabTestRestock',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('quantity_added', models.PositiveIntegerField()),
                ('supplier_name', models.CharField(blank=True, max_length=255)),
                ('batch_number', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('restocked_at', models.DateTimeField(auto_now_add=True)),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restocks', to='laboratory.labtest')),
                ('restocked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_test_restocks_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LabStockMovement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('movement_type', models.CharField(choices=[('RESTOCK', 'Restock'), ('CONSUMPTION', 'Consumption'), ('ADJUSTMENT', 'Adjustment')], max_length=20)),
                ('quantity', models.IntegerField()),
                ('previous_stock', models.PositiveIntegerField(default=0)),
                ('new_stock', models.PositiveIntegerField(default=0)),
                ('reason', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lab_request_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='laboratory.labrequestitem')),
                ('lab_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_movements', to='laboratory.labtest')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_stock_movements', to=settings.AUTH_USER_MODEL)),
                ('restock_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_movements', to='laboratory.labtestrestock')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
