# Generated by Django 6.0.3 on 2026-04-18 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital_name', models.CharField(default='Hospital Management System', max_length=255)),
                ('short_name', models.CharField(default='HMS', max_length=50)),
                ('hospital_address', models.TextField(blank=True)),
                ('hospital_phone', models.CharField(blank=True, max_length=50)),
                ('hospital_email', models.EmailField(blank=True, max_length=254)),
                ('hospital_website', models.URLField(blank=True)),
                ('hospital_motto', models.CharField(blank=True, max_length=255)),
                ('hospital_logo', models.ImageField(blank=True, null=True, upload_to='hospital/')),
                ('currency_symbol', models.CharField(default='₦', max_length=10)),
                ('timezone_label', models.CharField(default='Africa/Lagos', max_length=100)),
                ('default_e_card_fee', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('record_retention_days', models.PositiveIntegerField(default=3650)),
                ('backup_instructions', models.TextField(blank=True, help_text='Internal instructions for backup/export operations.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital Setting',
                'verbose_name_plural': 'Hospital Settings',
            },
        ),
    ]
