# Generated by Django 6.0.3 on 2026-04-20 14:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BackupOperationLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('operation_type', models.CharField(choices=[('BACKUP', 'Backup'), ('RESTORE', 'Restore')], max_length=20)),
                ('file_type', models.CharField(choices=[('DATABASE', 'Database'), ('MEDIA', 'Media'), ('XLSX', 'XLSX'), ('PDF', 'PDF'), ('JSON', 'JSON'), ('OTHER', 'Other')], default='DATABASE', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='backup_operations_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Backup Operation Log',
                'verbose_name_plural': 'Backup Operation Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
