# Generated by Django 6.0.3 on 2026-04-21 08:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_backupoperationlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RetentionExecutionLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('retention_days_used', models.PositiveIntegerField(default=3650)),
                ('consultations_archived', models.PositiveIntegerField(default=0)),
                ('admissions_archived', models.PositiveIntegerField(default=0)),
                ('patient_records_archived', models.PositiveIntegerField(default=0)),
                ('billings_archived', models.PositiveIntegerField(default=0)),
                ('notes', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('COMPLETED', 'Completed'), ('FAILED', 'Failed')], default='COMPLETED', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retention_runs_performed', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Retention Execution Log',
                'verbose_name_plural': 'Retention Execution Logs',
                'ordering': ['-created_at'],
            },
        ),
    ]
