# Generated by Django 6.0.3 on 2026-04-03 14:36

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('complaint', models.TextField(blank=True)),
                ('diagnosis', models.TextField(blank=True)),
                ('prescriptions', models.TextField(blank=True)),
                ('medication', models.TextField(blank=True)),
                ('laboratory_tests', models.TextField(blank=True)),
                ('notes', models.TextField(blank=True)),
                ('admitted', models.BooleanField(default=False)),
                ('discharged', models.BooleanField(default=False)),
                ('died', models.BooleanField(default=False)),
                ('complete', models.BooleanField(default=False)),
                ('consultation_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('REFERRED', 'Referred'), ('CANCELLED', 'Cancelled')], default='IN_PROGRESS', max_length=20)),
                ('consulted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultations_handled', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
