# Generated by Django 6.0.3 on 2026-03-31 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='consultation',
            name='prescriptions',
            field=models.TextField(blank=True),
        ),
    ]
