# Generated by Django 6.0.3 on 2026-03-31 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consultations', '0002_consultation_prescriptions'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='admitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='discharged_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='consultation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patient_record', to='consultations.consultation'),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='prescriptions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='patientrecord',
            name='record_type',
            field=models.CharField(choices=[('NURSE_NOTE', 'Nurse Note'), ('DOCTOR_CONSULTATION', 'Doctor Consultation')], default='NURSE_NOTE', max_length=30),
        ),
    ]
