# Generated by Django 6.0.3 on 2026-04-03 14:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
        ('waiting_room', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='triagerecord',
            name='waiting_room_entry',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_record', to='waiting_room.waitingroomentry'),
        ),
    ]
