# Generated by Django 6.0.3 on 2026-03-31 16:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_admitted_at_patient_discharged_at_and_more'),
        ('waiting_room', '0002_waitingroomentry_assigned_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientrecord',
            name='record_type',
            field=models.CharField(choices=[('CONSULTATION_SESSION', 'Consultation Session')], default='CONSULTATION_SESSION', max_length=30),
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse', models.PositiveIntegerField(blank=True, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('body_temperature', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('notes', models.TextField(blank=True)),
                ('is_consumed', models.BooleanField(default=False)),
                ('consumed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='triage_records_created', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triage_records', to='patients.patient')),
                ('waiting_room_entry', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_record', to='waiting_room.waitingroomentry')),
            ],
        ),
    ]
