# Generated by Django 6.0.3 on 2026-04-02 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_alter_patientrecord_record_type_triagerecord'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='hospital_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
