# Generated by Django 6.0.3 on 2026-04-03 14:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InpatientNote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('note_type', models.CharField(choices=[('DOCTOR', 'Doctor Note'), ('NURSE', 'Nurse Note')], max_length=20)),
                ('note', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MedicationAdministration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('route', models.CharField(choices=[('ORAL', 'Oral'), ('IV', 'IV'), ('IM', 'IM'), ('TOPICAL', 'Topical'), ('OTHER', 'Other')], default='ORAL', max_length=20)),
                ('administration_notes', models.TextField(blank=True)),
                ('administered_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Admission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('reason_for_admission', models.TextField(blank=True)),
                ('ward', models.CharField(blank=True, max_length=100)),
                ('bed_number', models.CharField(blank=True, max_length=50)),
                ('surgery_performed', models.BooleanField(default=False)),
                ('surgery_notes', models.TextField(blank=True)),
                ('further_lab_tests', models.TextField(blank=True)),
                ('visits_during_admission', models.TextField(blank=True)),
                ('admission_extra_costs', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGE_PENDING_NURSE', 'Pending Nurse Discharge Confirmation'), ('DISCHARGED', 'Discharged')], default='ACTIVE', max_length=40)),
                ('admitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('discharged_at', models.DateTimeField(blank=True, null=True)),
                ('discharge_summary', models.TextField(blank=True)),
                ('nurse_discharge_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admitted_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_created', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
