# Generated by Django 6.0.3 on 2026-04-02 07:34

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='admission_extra_costs',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=12),
        ),
        migrations.AddField(
            model_name='admission',
            name='further_lab_tests',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='nurse_discharge_confirmed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admissions_nurse_confirmed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='admission',
            name='nurse_discharge_note',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='surgery_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='admission',
            name='surgery_performed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='admission',
            name='visits_during_admission',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='admission',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DISCHARGE_PENDING_NURSE', 'Pending Nurse Discharge Confirmation'), ('DISCHARGED', 'Discharged')], default='ACTIVE', max_length=40),
        ),
    ]
