# Generated by Django 6.0.3 on 2026-04-03 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('admissions', '0002_initial'),
        ('patients', '0001_initial'),
        ('pharmacy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admissions', to='patients.patient'),
        ),
        migrations.AddField(
            model_name='inpatientnote',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='inpatientnote',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inpatient_notes_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='administered_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medications_administered', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='admission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medication_administrations', to='admissions.admission'),
        ),
        migrations.AddField(
            model_name='medicationadministration',
            name='prescription_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='administrations', to='pharmacy.prescriptionitem'),
        ),
    ]
