# Generated by Django 6.0.3 on 2026-04-14 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy', '0002_drugrestock_drugstockmovement'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescriptionitem',
            name='dosage',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='duration_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='frequency',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='prescriptionitem',
            name='route',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
